### ISSUE TITLE
Pull in the "obvci_appveyor_python_build_env.cmd" script?

### ISSUE THREAD

**Issue by pelson** [conda-forge/toolchain-feedstock#1]
The only reason that each and every feedstock pulls in obvious-ci is to have access to the [`obvci_appveyor_python_build_env.cmd` script](https://github.com/pelson/Obvious-CI/blob/master/scripts/obvci_appveyor_python_build_env.cmd) which configures the appropriate VC version. Given the nature of the toolchain package, it may make some sense to consider pulling that script into this package.

**Comment by pelson** [comment]
I'd be really interested to hear @msarahan and @patricksnape's thought on doing this. Is that script now entirely redundant due to recent conda-build changes anyway?

**Comment by jakirkham** [comment]
If it (or any part of it) is still necessary, I totally agree this would be the right home for it.

Also, @msarahan and @patricksnape, if either of you have any interest in being added as maintainers here, we would be more than happy to have both of you.

**Comment by msarahan** [comment]
Happy to be a maintainer.  I hope that script is redundant now, but I think because of CMake it might still be necessary.

**Comment by patricksnape** [comment]
I'm still working on getting this all straight in my head but I promise I'll get back as soon as possible. It should mean we know whether or not we even need scripts like this!

**Comment by jakirkham** [comment]
Excellent! Adding both of you in this PR ( https://github.com/conda-forge/toolchain-feedstock/pull/2 ).

**Comment by jakirkham** [comment]
Just as FYI, in order to actually use activate scripts on Windows (admittedly with the same hack we are using on Mac and Linux), we need a release of `conda` that contains the fixes for activate scripts on Windows ( https://github.com/conda/conda/pull/2365 ). So, we might want to wait moving in that direction, @pelson, until we see `conda` 4.1.

**Comment by jakirkham** [comment]
Have we come to any conclusion regarding @pelson's use case? The proposal put forward sounds very reasonable IMHO, but I'm still unclear on the status of things on Windows.

**Comment by patricksnape** [comment]
I still believe, as mentioned in the comments in my conda-build PR, that much of this environment activation doesn't need to be done. For example, it definitely doesn't need to be done for Python 2.7. Something needs to be done for Python 3.4 but I was trying to make it happen within conda-build without requiring activating the Windows SDK 7.1 before invoking conda-build.

**Comment by jakirkham** [comment]
As it seems we no longer need this in `conda-forge` ( https://github.com/conda-forge/conda-smithy/pull/392 ) and `conda-build` 2 & 3 have greatly improved the compiler story, going to close this out. Hope that is ok. If anyone feels there is something not adequately resolved here, please feel free to reopen.
