### ISSUE TITLE
Toolchain resets $CC and $CXX to the system default

### ISSUE THREAD

**Issue by wesm** [conda-forge/toolchain-feedstock#10]
What is the recommended solution for builds that require a newer version of gcc? For example, in Trusty Travis CI builds, gcc 4.8 is the default. We override this in our Travis CI build:

https://github.com/apache/parquet-cpp/blob/master/.travis.yml#L44

But it gets globbered by the toolchain setup.

**Comment by jakirkham** [comment]
At present, there isn't one. Sorry. 😞

We have a chat a few weeks back about getting a `gcc` package back (with a newer version probably). It looks like that will happen. Though I don't really know any details or what time frame this will happen on. Will keep you posted when we know more.

**Comment by jakirkham** [comment]
Ok, I think I might have missed some important context here. Is this a question about using the `toolchain` with `gcc` on Mac at conda-forge or outside of conda-forge? If the latter, I would recommend not using the `toolchain` ATM. Though we can certainly discuss whether we want to broaden its scope to include this use case.

**Comment by wesm** [comment]
Got it, yes, I was trying to use the toolchain outside conda forge (but depending on other conda-forge packages). Noted.

**Comment by jakirkham** [comment]
Think this is resolved. So closing it out. If not, please feel free to reopen (or ask me to). Thanks.
