### ISSUE TITLE
Pin toolchain to 2.0.0

### ISSUE THREAD

**Issue by isuruf** [conda-forge/toolchain-feedstock#22]
I'm not going to add this pinning to the maintenance script. I'll do PRs myself. Reasons are,

1. There are 407 feedstocks which means it would take months for the maintenance service to send out PRs
2. Maintenance script would not put `[skip ci]` in for pinning updates. 407 builds is too much for the CI to handle.

Here's an example, https://github.com/conda-forge/symengine-feedstock/pull/9.
@jakirkham, @ocefpaf, can you have a look and give the go ahead?

**Comment by isuruf** [comment]
ping

**Comment by isuruf** [comment]
ping

**Comment by jakirkham** [comment]
Honestly I don't really feel a need to pin the `toolchain`. That said, if people are wanting to pin the `toolchain` in their feedstocks, it should be easy enough to do.

**Comment by isuruf** [comment]
I'm no longer interested in this. See https://github.com/conda-forge/staged-recipes/pull/3093 for a new toolchain package.
