### ISSUE TITLE
why doesn't toolchain have gcc/llvm/binutils as actual dependencies?

### ISSUE THREAD

**Issue by notestaff** [conda-forge/toolchain-feedstock#28]
Should recipes that need compilation still add dependencies on gcc/llvm/binutils, in addition to the dependency on toolchain?

**Comment by jakirkham** [comment]
This duplicates the points raised in issue ( https://github.com/conda-forge/toolchain-feedstock/issues/27 ). So will close this out as a duplicate. Would encourage you to ask questions there after reading the thread. :)
