### ISSUE TITLE
make: Error -1073741819

### ISSUE THREAD

**Issue by xobs** [conda-forge/toolchain-feedstock#58]
When using `msys2:m2w64-toolchain` to compile Yosys, it always fails the first time when building `/src/base/abci/abcReorder.c`.  It succeeds on the second compile.

This is not a multithreaded build, so I suspect `make` is keeping filehandles open and they're getting exhausted, since this file is pretty far along in the build:

```
-> ABC: `` Compiling: /src/base/abci/abcRenode.c
-> ABC: `` Compiling: /src/base/abci/abcReorder.c
make[1]: *** [Makefile:175: src/base/abci/abcReorder.o] Error -1073741819
make[1]: Leaving directory 'D:/Software/Miniconda3/conda-bld/yosys_1571635349597/work/abc'
make: *** [Makefile:657: abc/abc-default] Error 2
```

This is an issue in a package of yosys that I'm building (https://github.com/xobs/conda-yosys/tree/283e5ff53837c5558cfe47130e625f72084c5cc2) and as a workaround I do the build twice now and ignore the return code from the first build.

**Comment by scopatz** [comment]
This is not the correct place reports on `msys2:m2w64-toolchain`. CC @mingwandroid @conda-forge/core

**Comment by xobs** [comment]
Sorry for the noise.  Where is the correct place to report such things?  And, more importantly, how can I figure that out on my own?  I don't see any sort of `maintainer` or `source repo` link on https://anaconda.org/msys2/m2w64-toolchain

**Comment by mingwandroid** [comment]
This will be your virus scanner. 99.99% guaranteed. The only one that doesn't break windows in fundamental ways that I have ever seen is Microsoft'windows defender. The rest are junk IMHO. 

Issues against packages on Anaconda Distro (as opposed to conda-forge) should be reported at https://github.com/ContinuumIO/anaconda-issues

**Comment by xobs** [comment]
I'm not using any sort of virus scanner, and Windows Defender is disabled.

I'll continue to investigate, and in the future I will post any issues I see with any Conda packages to the `anaconda-issues` tracker.

**Comment by jakirkham** [comment]
Are you mounting a remote drive? If so, perhaps the virus scanner is running on a different machine than the one you are using.

**Comment by xobs** [comment]
No, this is a local `D:\` SATA-connected drive

**Comment by jakirkham** [comment]
Is the drive encrypted?

**Comment by jakirkham** [comment]
Anyways if you are able to try another drive, that might be an interesting line of inquiry.

**Comment by xobs** [comment]
No, the drive isn't encrypted.

The only odd thing about this system is that it's running under qemu native, but that drive is passed through directly.

However, as you say, the virtualization and indirection are adding unnecessary variables to the equation, so I will try a different machine.  Since nobody else has reported this issue, it's probably a configuration or hardware problem on my end.
